# Generated by Django 4.0.3 on 2022-05-28 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.service'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.role'),
        ),
    ]
