# Generated by Django 4.0.3 on 2022-05-21 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='utilisateur', max_length=50, unique=True)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.service')),
            ],
        ),
    ]
