# Generated by Django 4.0.3 on 2022-05-21 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.service'),
        ),
    ]
