# Generated by Django 4.0.3 on 2022-03-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_users_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='anything', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='anything', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='surname',
            field=models.CharField(default='anything', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='anything', max_length=20),
        ),
    ]
