# Generated by Django 4.0.3 on 2022-04-05 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_users_email_alter_users_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='anything', max_length=150)),
                ('description', models.CharField(default='anything', max_length=250)),
                ('date', models.DateField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(default='anything', max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
