# Generated by Django 4.0.3 on 2022-04-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='place',
            field=models.CharField(default='anything', max_length=250),
        ),
    ]
