# Generated by Django 4.0.3 on 2022-04-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0002_declaration_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='validete',
            field=models.BooleanField(default=False),
        ),
    ]
