# Generated by Django 4.0.3 on 2022-04-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0003_declaration_validete'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
