# Generated by Django 4.0.3 on 2022-04-06 02:52

from django.db import migrations, models
import responsable.models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0004_declaration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='image',
            field=models.ImageField(blank=True, upload_to=responsable.models.filepath),
        ),
    ]
