# Generated by Django 4.0.3 on 2022-06-14 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport_archivé',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='anything', max_length=150)),
                ('description', models.TextField(default='anything')),
                ('date', models.DateField()),
                ('validate', models.BooleanField(default=False)),
                ('status', models.CharField(default='Non_traité', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to=services.models.filepath)),
                ('complement', models.CharField(default='anything', max_length=200)),
                ('send', models.BooleanField(default=False)),
                ('signalement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_user.signaux_archivé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='anything', max_length=150)),
                ('description', models.TextField(default='anything')),
                ('date', models.DateField()),
                ('validate', models.BooleanField(default=False)),
                ('status', models.CharField(default='Non_traité', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to=services.models.filepath)),
                ('complement', models.CharField(default='anything', max_length=200)),
                ('send', models.BooleanField(default=False)),
                ('signalement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_user.signaux')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
