# Generated by Django 4.0.3 on 2022-05-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0009_signaux_salle'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='signalement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_user.signaux'),
        ),
    ]
