# Generated by Django 4.0.3 on 2022-05-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_rapport_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='description',
            field=models.TextField(default='anything'),
        ),
    ]
