# Generated by Django 4.0.3 on 2022-06-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_notifyrapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifyrapp',
            old_name='an',
            new_name='rap',
        ),
    ]
