# Generated by Django 4.0.3 on 2022-05-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rapport_signalement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='status',
            field=models.CharField(default='Non_traité', max_length=20),
        ),
    ]
