# Generated by Django 4.0.3 on 2022-06-12 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0008_remove_signaux_archivé_rapport'),
        ('services', '0005_rapport_archivé'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport_archivé',
            name='signalement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_user.signaux_archivé'),
        ),
    ]
