# Generated by Django 4.0.3 on 2022-05-12 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home_user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catégorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=home_user.models.filepath)),
                ('description', models.TextField(default='none', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Signaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='none', max_length=50)),
                ('lieu', models.CharField(default='None', max_length=100)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('description', models.TextField(default='None', max_length=200)),
                ('send', models.BooleanField(default=False)),
                ('validate', models.BooleanField(default=False)),
                ('statut', models.CharField(default='en_cours', max_length=50)),
                ('complement', models.CharField(default='anything', max_length=200)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_user.catégorie')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='anything', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=home_user.models.filepath)),
                ('description', models.TextField(max_length=200)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(auto_now_add=True)),
                ('validate', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
