# Generated by Django 4.0.3 on 2022-06-14 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home_user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='anything', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=home_user.models.filepath)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('validate', models.BooleanField(default=False)),
                ('send', models.BooleanField(default=False)),
                ('status', models.CharField(default='Non_traité', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Catégorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=home_user.models.filepath)),
                ('description', models.TextField(default='none', max_length=20)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.service')),
            ],
        ),
        migrations.CreateModel(
            name='Signaux_archivé',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='none', max_length=50)),
                ('lieu', models.CharField(default='None', max_length=100)),
                ('salle', models.CharField(default='None', max_length=100)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('description', models.TextField(default='None', max_length=500)),
                ('send', models.BooleanField(default=False)),
                ('validate', models.BooleanField(default=False)),
                ('statut', models.CharField(default='Non_traité', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=home_user.models.filepath)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_user.catégorie')),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.service')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='none', max_length=50)),
                ('lieu', models.CharField(default='None', max_length=100)),
                ('salle', models.CharField(default='None', max_length=100)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('description', models.TextField(default='None', max_length=500)),
                ('send', models.BooleanField(default=False)),
                ('validate', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('Traité', 'Traité'), ('En_cours', 'En_cours'), ('Non_traité', 'Non_traité'), ('Rejeté', 'Rejeté')], default='Non_traité', max_length=50)),
                ('complement', models.CharField(default='anything', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, upload_to=home_user.models.filepath)),
                ('rapport_ajouter', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_user.catégorie')),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.service')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('an', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_user.annonce')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='touser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=2000)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('sig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_user.signaux')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
