# Generated by Django 4.0.3 on 2022-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_fin',
            field=models.DateField(),
        ),
    ]
