# Generated by Django 4.0.3 on 2022-06-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaux',
            name='pere',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signaux',
            name='rattacher',
            field=models.BooleanField(default=False),
        ),
    ]
