# Generated by Django 4.0.3 on 2022-05-28 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notification_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home_user.signaux'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='notification_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
