# Generated by Django 4.0.3 on 2022-05-12 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('home_user', '0002_alter_annonce_date_debut_alter_annonce_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaux',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.service'),
        ),
    ]
