# Generated by Django 4.0.3 on 2022-06-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_name'),
        ('home_user', '0002_signaux_pere_signaux_rattacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaux',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='home_user.catégorie'),
        ),
        migrations.AlterField(
            model_name='signaux',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.service'),
        ),
        migrations.AlterField(
            model_name='signaux_archivé',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='home_user.catégorie'),
        ),
        migrations.AlterField(
            model_name='signaux_archivé',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.service'),
        ),
    ]
