# Generated by Django 4.0.3 on 2022-05-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0002_alter_notifications_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catégorie',
            name='description',
            field=models.TextField(default='none', max_length=20),
        ),
    ]
