# Generated by Django 4.0.3 on 2022-05-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0003_alter_catégorie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='signaux',
            name='description',
            field=models.TextField(default='None', max_length=500),
        ),
    ]
