# Generated by Django 4.0.3 on 2022-05-12 18:48

from django.db import migrations, models
import home_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0003_signaux_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaux',
            name='image',
            field=models.ImageField(blank=True, upload_to=home_user.models.filepath),
        ),
    ]
