# Generated by Django 4.0.3 on 2022-06-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0003_alter_signaux_category_alter_signaux_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaux_archivé',
            name='pere',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='signaux_archivé',
            name='rapport_ajouter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signaux_archivé',
            name='rattacher',
            field=models.BooleanField(default=False),
        ),
    ]
