# Generated by Django 4.0.3 on 2022-05-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0004_signaux_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='publish',
        ),
    ]
