# Generated by Django 4.0.3 on 2022-06-12 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home_user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_alter_role_service_alter_users_role'),
        ('home_user', '0004_alter_annonce_description_alter_signaux_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catégorie',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='users.service'),
        ),
        migrations.CreateModel(
            name='Signaux_archivé',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='none', max_length=50)),
                ('lieu', models.CharField(default='None', max_length=100)),
                ('salle', models.CharField(default='None', max_length=100)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('description', models.TextField(default='None', max_length=500)),
                ('send', models.BooleanField(default=False)),
                ('validate', models.BooleanField(default=False)),
                ('statut', models.CharField(default='Non_traité', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=home_user.models.filepath)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home_user.catégorie')),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.service')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
