# Generated by Django 4.0.3 on 2022-05-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0005_remove_annonce_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaux',
            name='complement',
            field=models.CharField(default='anything', max_length=200, null=True),
        ),
    ]
