# Generated by Django 4.0.3 on 2022-05-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0006_alter_signaux_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaux',
            name='statut',
            field=models.CharField(default='non_traité', max_length=50),
        ),
    ]
