# Generated by Django 4.0.3 on 2022-05-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0007_alter_signaux_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='status',
            field=models.CharField(default='non_valider', max_length=255),
        ),
    ]
