# Generated by Django 4.0.3 on 2022-06-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0007_signaux_archivé_rapport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaux_archivé',
            name='rapport',
        ),
    ]
