# Generated by Django 4.0.3 on 2022-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0008_annonce_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaux',
            name='salle',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
