# Generated by Django 4.0.3 on 2022-06-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0009_signaux_rapport_ajouter'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaux',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
