# Generated by Django 4.0.3 on 2022-05-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0009_signaux_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='status',
            field=models.CharField(default='Non_valider', max_length=255),
        ),
        migrations.AlterField(
            model_name='signaux',
            name='statut',
            field=models.CharField(default='Non_traité', max_length=50),
        ),
    ]
