# Generated by Django 4.0.3 on 2022-05-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0011_alter_annonce_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signaux',
            name='send',
        ),
    ]
