# Generated by Django 4.0.3 on 2022-05-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0012_remove_signaux_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signaux',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
