# Generated by Django 4.0.3 on 2022-05-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0013_annonce_send_signaux_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaux',
            name='statut',
            field=models.CharField(choices=[('Traité', 'Traité'), ('En_cours', 'En_cours')], default='Non_traité', max_length=50),
        ),
    ]
