# Generated by Django 4.0.3 on 2022-05-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_user', '0014_alter_signaux_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaux',
            name='statut',
            field=models.CharField(choices=[('Traité', 'Traité'), ('En_cours', 'En_cours'), ('Non_traité', 'Non_traité'), ('Rejeté', 'Rejeté')], default='Non_traité', max_length=50),
        ),
    ]
